spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true}
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
jwt:
  secret: drmsSuperSecretKeyForJwtTokenGenerationMustBe32CharsLong
  expiration: 86400000

feign:
  circuitbreaker:
    enabled: true

rabbitmq:
  exchange:
    name: notification_exchange
  device:
    added:
      routing:
        key:
          device_added_key
    assigned:
      routing:
        key:
          device_assigned_key
  admin:
    queue: admin_queue
  employee:
    queue: employee_queue

  repair:
    raised:
      routing:
        key: repair_raised_key
    acknowledged:
      routing:
        key: repair_acknowledged_key
    completed:
      routing:
        key: repair_completed_key
    closed:
      routing:
        key: repair_closed_key
