spring:
  application:
    name: eureka-server


server:
  port: 8761

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
