spring:
  application:
    name: device-service

  datasource:
    url: jdbc:mysql://localhost:3306/device_db
    username: ${USER_NAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
